# fly.toml app configuration file generated for finapp-invest-python on 2025-01-04T19:16:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'finapp-invest-python'
primary_region = 'cdg'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[processes]
  app = "flask --app src.app.main run --host=0.0.0.0 --port=8080"
